# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "olap4r"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Filip Tepper"]
  s.date = "2012-10-22"
  s.description = "olap4j wrapper for JRuby"
  s.email = "filip@tepper.pl"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/olap4j.jar",
    "lib/olap4r.rb",
    "lib/olap4r/cellset.rb",
    "lib/olap4r/connection.rb",
    "lib/olap4r/query_builder.rb",
    "lib/olap4r/rowset.rb",
    "olap4r.gemspec",
    "spec/config.yml.example",
    "spec/connection_spec.rb",
    "spec/fixtures/FoodMart.xml",
    "spec/query_builder_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/Freeport-Metrics/olap4r"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "olap4j wrapper for JRuby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jruby-openssl>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.8.2.1"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<olap4r-mondrian>, ["~> 0.1.0"])
      s.add_development_dependency(%q<olap4r-xmla>, ["~> 0.1.0"])
    else
      s.add_dependency(%q<jruby-openssl>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.11.0"])
      s.add_dependency(%q<yard>, ["~> 0.8.2.1"])
      s.add_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<olap4r-mondrian>, ["~> 0.1.0"])
      s.add_dependency(%q<olap4r-xmla>, ["~> 0.1.0"])
    end
  else
    s.add_dependency(%q<jruby-openssl>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.11.0"])
    s.add_dependency(%q<yard>, ["~> 0.8.2.1"])
    s.add_dependency(%q<bundler>, ["~> 1.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<olap4r-mondrian>, ["~> 0.1.0"])
    s.add_dependency(%q<olap4r-xmla>, ["~> 0.1.0"])
  end
end

